meta_product_name: "Vestigium"
meta_title: "Vestigium - Focus on news sentiment"
meta_description: "We at Vestigium focus on making you more aware of the sentiment of the news you consume"
meta_image: "cover.png" # should exist in `app/assets/images/`
